grammar_task:
  description: >
    Edit the text file content below to correct grammar and punctuation issues:

    {notes}

    Ensure all changes preserve the original meaning and maintain academic tone.
    Your final result MUST be a fully edited version of the file with corrections applied.
    Save your output as an edited version to be passed to the final editor.
  # Input: {notes}
  expected_output: >
    The cleaned-up version of the text with improved grammar and clarity.
  agent: grammar_expert
  output_key: grammar_output

fact_check_task:
  description: >
    Review the following notes for factual inaccuracies:

    {notes}

    For each inaccuracy, apply a correction and cite credible sources if possible.
    Your final result MUST be a corrected version of the content.
    Save your output to be passed to the final editor.

  expected_output: >
    A fact-checked report listing inaccuracies found, corrections, and supporting references.
  agent: factual_expert
  input_keys: grammar_output
  output_key: fact_output

outline_task:
  description: >
    Convert the following raw notes into a structured outline using the Outline Method format.

    {notes}

    The Outline Method is a hierarchical note-taking system where main topics are aligned to the left, and supporting details are nested underneath using indentation. Follow these formatting rules:
    - Main points should be labeled as numbered headings (## [1. Topic Name]).
    - Supporting ideas should be bullet points under the heading.
    - Sub-details or examples should be indented further as nested bullet points.

    Use the following **Markdown** structure:
    ## [1. Main Topic]  
    - [Brief description or key idea]  
    - [Supporting detail or explanation]  
      - [Optional sub-detail or example]

    ## [2. Next Topic]  
    - [Key point]  
      - [Subpoint]  
      - [Subpoint]

    ## [3. Another Topic]  
    - [Summary of concept]  
    - [Real-world application or example]

    ## [4. Final Topic]  
    - [Challenges / Pros / Cons / Impacts]

    Your output MUST be a clean, well-organized **Markdown** document using this layout.
  expected_output: >
    A Markdown document using the Outline Method format saved to report.md
  agent: outline_expert
  input_keys: fact_output
  # output_key: formatted_notes

cornell_task:
  description: >
    Convert the following notes into the Cornell Method format:

    {notes}

    Format the result with three clearly defined sections:
    - Cue column with keywords or questions: 
    - Notes section with expanded information: Main ideas, details, and examples 
    - Summary at the bottom

    Output must be in Markdown format.
    Ensure the layout is:
      # Cornell Notes
      ## Cues
      ## Notes
      ## Summary
    
  expected_output: >
    A Markdown document using the Cornell Method format saved to report.md
  agent: cornell_expert
  input_keys: fact_output
  

boxing_task:
  description: >
    Convert the following notes into the Boxing Method format using clean, structured Markdown.

    {notes}

    The Boxing Method organizes information into clearly labeled "boxes" or sections, 
    each with a concise title and bullet points of related details. End with a summary 
    that captures key insights from all boxes.

    Your response MUST follow this Markdown layout:
    ## Box 1: [Title or Topic]
    - [Key points or supporting details]
    - [Relevant examples or facts]

    ## Box 2: [Next Topic]
    - [Main ideas and explanations]
    - [Additional supporting notes]

    ## Box 3: [Another Topic]
    - [Concept summary or definitions]
    - [Contextual examples]

    ## Summary
    - [Brief recap or conclusions drawn across topics]

    Ensure formatting is clean and readable. Avoid raw text dumps. Use concise bullets and appropriate headings.

      ## Summary
  expected_output: >
    A well-organized Markdown document using the Boxing Method structure, saved as `report.md`
  agent: boxing_expert
  input_keys: fact_output
  

flashcard_task:
  description: >
    Create flashcards from the following notes:

    {notes}

    Rules:
    - Each flashcard must have a clear question and concise answer.
    - Focus on key facts, definitions, dates, and concepts.
    - Format as a Markdown list:

      - **Q: What is X?**  
        **A:** Explanation...

    - Generate 5–15 cards depending on the content.

    Your final answer MUST be a set of markdown-formatted Q&A flashcards.
    Save your output to `flashcards.md`.
  agent: flashcard_expert
  input_keys: fact_output
  expected_output: >
   A set of markdown flashcards saved to flashcards.md
